//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_OfflineApplications
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BankVerificationNumber { get; set; }
        public string Mobilenumber { get; set; }
        public string PersonalEmail { get; set; }
        public string PermanentAddress { get; set; }
        public string Landmark { get; set; }
        public string Closestbuststop { get; set; }
        public string LGA { get; set; }
        public Nullable<int> LGA_FK { get; set; }
        public string Stateofresidence { get; set; }
        public Nullable<int> StateOfResidence_FK { get; set; }
        public string TemporaryAddress { get; set; }
        public string TempLandmark { get; set; }
        public string TempClosestBuststop { get; set; }
        public string TempLGA { get; set; }
        public Nullable<int> TempLGA_FK { get; set; }
        public string TempState { get; set; }
        public Nullable<int> TempState_FK { get; set; }
        public string StateCode { get; set; }
        public string NyscState { get; set; }
        public Nullable<int> NyscState_FK { get; set; }
        public string NyscLGA { get; set; }
        public Nullable<int> NyscLGA_FK { get; set; }
        public string NyscEmployer { get; set; }
        public string NyscAddress { get; set; }
        public Nullable<System.DateTime> NyscExpectedPassoutdate { get; set; }
        public string NyscCDSDay { get; set; }
        public string NyscCDsGroup { get; set; }
        public Nullable<double> Netmonthlyincome { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string EmergencyContactHomeaddress { get; set; }
        public string EmergencyContactPhonenumber { get; set; }
        public string EmergencyContactEmailAddress { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public Nullable<double> Tenure { get; set; }
        public Nullable<double> Monthsleft { get; set; }
        public Nullable<double> DefaultMonthsowed { get; set; }
        public Nullable<double> RepaymentAmount { get; set; }
        public string Anyexistingloan { get; set; }
        public Nullable<double> ExistingLoanOutstandingAmount { get; set; }
        public Nullable<double> ExistingLoanMonthsLeft { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<System.DateTime> DateDisbursed { get; set; }
    }
}
