//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Sheet
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Surname { get; set; }
        public string Other_Names { get; set; }
        public string Gender { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Bank_Verification_Number { get; set; }
        public string Mobile_number { get; set; }
        public string Personal_Email { get; set; }
        public string Permanent_Address { get; set; }
        public string Landmark { get; set; }
        public string Closest_bust_stop { get; set; }
        public string LGA { get; set; }
        public string State_of_residence { get; set; }
        public string Temporary_Address { get; set; }
        public string TempLandmark { get; set; }
        public string TempClosest_Bust_stop { get; set; }
        public string TempLGA { get; set; }
        public string TempState { get; set; }
        public string State_Code { get; set; }
        public string NyscState { get; set; }
        public string NyscLGA { get; set; }
        public string NyscEmployer { get; set; }
        public string NyscAddress { get; set; }
        public Nullable<System.DateTime> NyscExpected_Pass_out_date { get; set; }
        public string NyscCDS_Day { get; set; }
        public string NyscCDs_Group { get; set; }
        public Nullable<double> Net_monthly_income { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string EmergencyContactHome_address { get; set; }
        public string EmergencyContactPhone_number { get; set; }
        public string EmergencyContactEmail_Address { get; set; }
        public Nullable<double> Loan_Amount { get; set; }
        public Nullable<double> Tenure { get; set; }
        public Nullable<double> Months_left { get; set; }
        public Nullable<double> Default_Months_owed { get; set; }
        public Nullable<double> Repayment_Amount { get; set; }
        public string Any_existing_loan { get; set; }
        public Nullable<double> ExistingLoanOutstanding_Amount { get; set; }
        public Nullable<double> ExistingLoanMonths_Left { get; set; }
        public string Bank_Name { get; set; }
        public string Account_Number { get; set; }
        public string Account_Name { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
        public Nullable<System.DateTime> Date_Disbursed { get; set; }
        public string F49 { get; set; }
        public string F50 { get; set; }
        public string F51 { get; set; }
    }
}
