//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanksManager
    {
        public int ID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Othernames { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string BankName { get; set; }
        public string EnrollmentBranch { get; set; }
        public string Nationlaity { get; set; }
        public string Marital_Status { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<int> VerifiedStatus { get; set; }
        public string ServiceResponse { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string ValueDate { get; set; }
    }
}
