//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerLoanDetail
    {
        public int ID { get; set; }
        public int LoanApplication_FK { get; set; }
        public string EmployerID { get; set; }
        public string OfficialEmailAddress { get; set; }
        public string Occupation { get; set; }
        public string Designation { get; set; }
        public Nullable<int> EmploymentStatus_FK { get; set; }
        public string Department { get; set; }
        public Nullable<double> NetMonthlyIncome { get; set; }
        public string LandMark { get; set; }
        public string ClosestBusStop { get; set; }
        public string LGA_FK { get; set; }
        public Nullable<int> LengthOfServiceInYrs { get; set; }
        public Nullable<int> LengthOfServiceInMth { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> IsVisible { get; set; }
    }
}
