//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int ID { get; set; }
        public Nullable<int> InstitutionType_FK { get; set; }
        public string Name { get; set; }
        public string InstitutionCode { get; set; }
        public string InstitutionAddress { get; set; }
        public string InstitutionEmailAddress { get; set; }
        public string InstitutionPhoneNo { get; set; }
        public string ContactPhoneNo { get; set; }
        public string ContactEmailAddress { get; set; }
        public string HeadOfInstition { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
