//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGA
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int State_FK { get; set; }
        public string Audit { get; set; }
        public int IsVisible { get; set; }
    }
}
