//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSerialNo
    {
        public int ID { get; set; }
        public Nullable<int> NYSCSerialNo { get; set; }
        public Nullable<int> PayrollSerialNo { get; set; }
    }
}
