//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanLedger
    {
        public int ID { get; set; }
        public Nullable<int> Institution_FK { get; set; }
        public string ApplicantID { get; set; }
        public Nullable<System.DateTime> TranxDate { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string RefNumber { get; set; }
        public string PartnerRefNumber { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<int> PaymentFlag_FK { get; set; }
    }
}
