//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInterestRate
    {
        public int ID { get; set; }
        public Nullable<int> LoanType_FK { get; set; }
        public double InterestRate { get; set; }
        public Nullable<int> LoanTenure { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ValueTime { get; set; }
        public string ValueDate { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<int> Institution_FK { get; set; }
    }
}
