//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class NyscLoanApplication
    {
        public int ID { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> Title_FK { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Othernames { get; set; }
        public Nullable<int> Gender_FK { get; set; }
        public Nullable<int> MaritalStatus_FK { get; set; }
        public string DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ContactAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Landmark { get; set; }
        public string ClosestBusStop { get; set; }
        public Nullable<int> StateofResidence_FK { get; set; }
        public Nullable<int> LGA_FK { get; set; }
        public string TemporaryAddress { get; set; }
        public string TempLandmark { get; set; }
        public string TempClosestBusStop { get; set; }
        public Nullable<int> TempLGA_FK { get; set; }
        public Nullable<int> TempStateofResidence_FK { get; set; }
        public string StateCode { get; set; }
        public Nullable<int> NyscStateofResidence_FK { get; set; }
        public Nullable<int> NyscLGA_FK { get; set; }
        public string Employer { get; set; }
        public string OfficialAddress { get; set; }
        public string PassOutMonth { get; set; }
        public string CDSDay { get; set; }
        public string CDSGroup { get; set; }
        public Nullable<double> NetMonthlyIncome { get; set; }
        public string EMG_FullName { get; set; }
        public string EMG_Relationship { get; set; }
        public string EMG_PhoneNumber { get; set; }
        public string EMG_EmailAddress { get; set; }
        public string EMG_HomeAddress { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public Nullable<int> LoanTenure { get; set; }
        public Nullable<bool> ExistingLoan { get; set; }
        public Nullable<double> ExistingLoan_OutstandingAmount { get; set; }
        public Nullable<int> ExistingLoan_NoOfMonthsLeft { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string BVN { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> NYSCApplicationStatus_FK { get; set; }
        public string NyscIdCardFilePath { get; set; }
        public string STA_FilePath { get; set; }
        public string ReferralCode { get; set; }
        public string LoanComment { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string CreatedBy { get; set; }
        public string CustomerNo { get; set; }
        public string LoanSerialNo { get; set; }
        public string MarketingChannel { get; set; }
        public Nullable<double> RepaymentAmount { get; set; }
        public string Audit { get; set; }
    }
}
