//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int ID { get; set; }
        public Nullable<int> User_FK { get; set; }
        public string PartnerID { get; set; }
        public string PartnerKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactPerson { get; set; }
        public string ContactAddress { get; set; }
        public string TokenVal { get; set; }
        public Nullable<double> myTokenTime { get; set; }
    }
}
