//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLoanDetail
    {
        public int ID { get; set; }
        public int LoanApplication_FK { get; set; }
        public string MatricNumber { get; set; }
        public string Institution { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string CourseOfStudy { get; set; }
        public string InstitutionAddress { get; set; }
        public string YearOfAdmission { get; set; }
        public string YearOfExpectedCompletion { get; set; }
        public Nullable<int> CurrentLevel_FK { get; set; }
        public Nullable<int> CurrentSemester_FK { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> IsVisible { get; set; }
    }
}
