//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string PhoneNumber { get; set; }
        public string PaswordVal { get; set; }
        public string EmailAddress { get; set; }
        public string UserAddress { get; set; }
        public Nullable<int> ResetPassword { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string PinNumber { get; set; }
        public Nullable<int> Title_FK { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> EmploymentStatus_FK { get; set; }
        public Nullable<int> StateofResidence_FK { get; set; }
        public Nullable<int> LGA_FK { get; set; }
        public string ContactAddress { get; set; }
        public string DateOfBirth { get; set; }
        public string ReferralCode { get; set; }
        public string MyReferralCode { get; set; }
        public string Audit { get; set; }
        public Nullable<int> ReferralLevel { get; set; }
    }
}
