//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessA.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int ID { get; set; }
        public int User_FK { get; set; }
        public int Role_FK { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
    }
}
